name: gruppo_twitch
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - pip
  - pip:
    - Flask
    - transformers
    - torch
    - torchvision
    - torchaudio
    - opencv-python
    - streamlink
    - tensorflow